on:
  push:
    branches: [main]

jobs:
  compila:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: instal·lar dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0"
      - run: dotnet build
      - name: "Tests unitaris"
        run: dotnet test VaquesBackendTests
      - name: "Iniciar sistema"
        run: docker-compose up -d
      - name: "Tests integracio"
        run: dotnet test vaquesUiTest
